### ISSUE TITLE
[Feature Request] DesktopCamera Support toggle post processing.

### ISSUE THREAD

**Issue by Toys0125** [Arion-Kun/TogglePostProcessing#7]
I noticed that even with the post-processing set to off the cam in DesktopCamera would still show with it on.
Made a cross-post to that specific mod. [https://github.com/nitrog0d/DesktopCamera/issues/82](https://github.com/nitrog0d/DesktopCamera/issues/82)

**Comment by JustArion** [comment]
#8 Should fix this compatibility issue / feature request

See [2.0.7 Pre-Release](https://github.com/Arion-Kun/PostProcessing/releases/tag/v2.0.7p) if that fixed it.
